### ISSUE TITLE
Initializing zero-valued structs with zero values is pointless, and copying mutexes is actively bad

### ISSUE THREAD

**Issue by tv42** [hotei/tokenbucket#1]
Happened to stumble on this.. Lines 35-36, assigning to tb.lock, are not needed there.

https://github.com/hotei/tokenbucket/blob/8b9da872bc3d4a0bf842434534ccc0ba5ce803b8/tokenbucket.go#L35-36

```
    var tb TokenBucket
    tb.fillInterval = fillTime
    tb.capacity = capacity
    tb.lastCount = capacity
    tb.lastCheckTime = time.Now()
    var lock sync.Mutex
    tb.lock = lock
    return &tb
```

**Comment by hotei** [comment]
Don't remember why I felt the need to do this at the time but you're correct that it is redundant.  It doesn't effect the programs correctness, just makes for a little less efficiency.  I've removed the offending lines.  Thanks for checking.
